---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: cf-service-resource
  path: gopath/src/github.com/phopper-pivotal/cf-service-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/phopper-pivotal/cf-service-resource/scripts/ci
