jobs:
- name: build-cf-service-resource-image
  public: false
  plan:
  - aggregate:
    - get: buildroot-base-image
      params: {save: true}
    - get: cf-service-resource
      trigger: true
  - task: resource-unit
    file: cf-service-resource/build.yml
  - put: cf-service-resource-image
    params:
      load_base: buildroot-base-image
      build: built-resource

resources:
- name: cf-service-resource
  type: git
  source:
    uri: https://github.com/idahobean/cf-service-resource.git
    branch: master

- name: cf-service-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: {{docker-repository}}

- name: buildroot-base-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: curl
